"""Bundle the existing study into one portable HTML file, without new dependencies."""

import base64
import json
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parent
PAGES = ("index.html", "catalog.html", "entry.html", "about.html")
ASSETS = ("assets/sea.png", "assets/path.png", "concept-gallery.png", "concept-catalog.png")


def build():
    pages = {}
    for name in PAGES:
        source = (ROOT / name).read_text()
        body = re.search(r'<body data-page="([^"]+)" class="([^"]+)">([\s\S]*)</body>', source)
        assert body, f"Cannot locate the study body in {name}"
        pages[name] = {
            "page": body[1],
            "theme": body[2],
            "body": body[3],
            "title": re.search(r"<title>(.*?)</title>", source)[1],
        }
    assets = {
        name: "data:image/png;base64," + base64.b64encode((ROOT / name).read_bytes()).decode()
        for name in ASSETS
    }
    payload = json.dumps({"pages": pages, "assets": assets}, ensure_ascii=False).replace("<", "\\u003c")
    icon = "data:image/svg+xml;base64," + base64.b64encode((ROOT / "assets/mark.svg").read_bytes()).decode()
    styles = (ROOT / "site.css").read_text()
    scripts = "\n".join(
        "<script>\n" + (ROOT / name).read_text().replace("</script", "<\\/script") + "\n</script>"
        for name in ("content.js", "site.js", "offline.js")
    )
    output = f'''<!doctype html>
<!-- Generated by build_offline.py. Edit the study sources and rebuild. -->
<html lang="zh-CN"><head><meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta name="color-scheme" content="light"><meta name="robots" content="noindex">
<title>Myshkin 451 — 离线设计预览</title><link rel="icon" href="{icon}">
<style>{styles}
.offline-concept {{ width: min(94vw, 1100px); max-height: 92dvh; border: 0; padding: 0; background: #f8f9fb; color: #172c42; }}
.offline-concept::backdrop {{ background: #152331bb; }}
.offline-concept header {{ position: sticky; top: 0; display: flex; align-items: center; justify-content: space-between; padding: 12px 20px; background: #f8f9fb; border-bottom: 1px solid #d8dce2; gap: 16px; }}
.offline-concept h2 {{ font-size: 16px; font-weight: 500; }}
.offline-concept button {{ padding: 9px 12px; font-size: 14px; }}
.offline-concept img {{ width: 100%; height: auto; }}
body:has(.offline-concept[open]) {{ overflow: hidden; }}
</style></head><body>
<div id="offline-app"></div>
<dialog id="offline-concept" class="offline-concept" aria-labelledby="offline-concept-title">
<header><h2 id="offline-concept-title">效果图</h2><form method="dialog"><button aria-label="关闭效果图">关闭 ×</button></form></header>
<img id="offline-concept-image" alt=""></dialog>
<noscript><p>请在启用 JavaScript 的浏览器中打开此离线网页。</p></noscript>
<script type="application/json" id="offline-data">{payload}</script>
{scripts}
</body></html>
'''
    (ROOT / "offline.html").write_text(output)
    print(f"Built offline.html: {len(output.encode()) / 1024 / 1024:.2f} MiB, {len(pages)} pages, {len(assets)} embedded images")


if __name__ == "__main__":
    build()
