import type { Entry, Settings } from './types'

export const defaultSettings: Settings = {
  name: 'Myshkin 451',
  intro: '',
  about: '',
  homeView: 'grid',
}

const base: Omit<Entry, 'id' | 'title' | 'kind'> = {
  summary: '',
  body: '',
  topics: [],
  cover: '',
  photos: [],
  destination: '',
  status: 'published',
  createdAt: '2026-09-18T00:00:00.000Z',
  updatedAt: '2026-09-18T00:00:00.000Z',
  publishedAt: '2026-09-18T00:00:00.000Z',
  featured: false,
  discussion: true,
  sample: true,
}

export const sampleEntries: Entry[] = [
  {
    ...base,
    id: 'coast',
    kind: 'photo',
    title: '海与山',
    summary: '',
    topics: ['自然', '视觉'],
    cover: './assets/sea.png',
    featured: true,
    body: '两张 AI 生成图片，用于展示相册排版。',
    photos: [
      {
        id: 'sea',
        src: './assets/sea.png',
        alt: '海浪经过深色礁石，白色浪花铺开。',
        caption: '海面',
        credit: 'AI 生成样例',
      },
      {
        id: 'path',
        src: './assets/path.png',
        alt: '沿海山坡上的一条小路，远处是海。',
        caption: '山路',
        credit: 'AI 生成样例',
      },
    ],
  },
  {
    ...base,
    id: 'image-space',
    kind: 'writing',
    featured: true,
    title: '给图片留一点空间',
    summary: '图片的大小、顺序和周围的空白，都会改变观看的方式。',
    topics: ['视觉', '设计'],
    body: '这一页是为检验中文阅读体验编写的排版样文，并非作者已发表的文章。\n\n## 从一张图开始\n\n同一张照片，放在手机上与印在书里，看到的细节往往不同。屏幕上的图像可以放大，手中的书却有固定的边界。排版需要回应这些差别。\n\n先把照片放到页面上，不急着加标题、说明与边框。看看它在多大的尺寸下更舒服，画面里有没有需要保留的边缘。\n\n## 两张图之间\n\n图片放在一起后，新的关系就出现了。相似的颜色会让视线自然地移动，方向相反的线条则可能让人停一下。排列的顺序也会改变这种感受。\n\n> 有时，调整两张图之间的距离，比再添一段说明更有效。\n\n一组照片未必需要整齐划一。横幅适合展开，竖幅可以稍窄，细节图可以靠近它所解释的部分。统一的边距能把这些变化留在同一个版面里。\n\n## 回到阅读\n\n图像之后，还要给正文一个容易重新进入的位置。图注短一些，行距放松一点，正文不要突然变得很宽。页面的节奏由这些具体选择慢慢建立。',
  },
  {
    ...base,
    id: 'color-study',
    kind: 'project',
    title: '色彩练习',
    summary: '选两种颜色，调整方向，做一张自己的渐变。',
    topics: ['视觉', '互动'],
    destination: '#/play/color',
    artwork: 'color',
    featured: true,
    body: '一个可直接使用的浏览器小工具。调整两端颜色与角度，查看实时效果，再复制 CSS 或下载 SVG。所有计算在你的浏览器中完成。',
  },
  {
    ...base,
    id: 'reading',
    kind: 'writing',
    title: '读书笔记的几种写法',
    summary: '摘录、提问和短评，各自适合记下什么。',
    topics: ['阅读'],
    body: '这一页是排版样文，不代指作者真实的读书笔记，也没有引用某一本书。\n\n## 摘录\n\n有些句子值得保留原来的样子。摘录时记下书名、章节和页码，之后才找得回来。再添一句自己为什么留下它，往往比多摘几段更有用。\n\n## 提问\n\n读不懂的地方可以先记成问题。作者在回应谁？这个结论依赖什么前提？换一个例子还成立吗？不必当场回答，重读的时候再回来看看。\n\n## 短评\n\n读完一章，用几句话说明它在讲什么，再写下自己赞同或保留的地方。短评不需要覆盖全部内容。只要记清当时的一处理解，下次打开就有了起点。\n\n摘录、提问与短评可以写在同一页。选择哪一种，取决于此刻想留下什么。',
  },
  {
    ...base,
    id: 'path',
    kind: 'photo',
    title: '山路',
    summary: '沿海的坡地与一条小路。',
    topics: ['自然'],
    cover: './assets/path.png',
    photos: [
      {
        id: 'path-single',
        src: './assets/path.png',
        alt: '一条小路穿过绿色山坡，远处是淡蓝色的海面。',
        caption: '山路',
        credit: 'AI 生成样例',
      },
    ],
  },
  {
    ...base,
    id: 'this-site',
    kind: 'project',
    title: '这个网站',
    summary: '本网站的源代码与开发记录。',
    topics: ['设计'],
    destination: 'https://github.com/myshkin451/myshkin451.com',
    artwork: 'site',
    body: '这里是本次网站设计的项目样页，链接指向当前公开仓库。\n\n## 当前版本\n\n这一轮实现公开浏览、内容编辑和访客交流的前端体验。本机发布的内容仅保存在当前浏览器中。真实账号、邮件与多人留言将在后端接入后提供。\n\n## 继续修改\n\n可以在工作台新建文章、上传照片或添加项目，再回到首页查看。已有样例与自己的内容可以分开浏览。',
  },
  ...[
    {
      id: 'note-sample-window',
      body: '雨停了，窗台上还在滴水。\n\n把窗开了一会儿，房间里有了秋天的气味。',
      topics: ['日常'],
      publishedAt: '2026-09-21T09:42:00.000Z',
    },
    {
      id: 'note-sample-book',
      body: '书看到一半，突然想回去重读第一章。\n\n有些开头，大概要等读完以后才算真的读过。',
      topics: ['阅读'],
      publishedAt: '2026-09-20T14:16:00.000Z',
    },
    {
      id: 'note-sample-link',
      body: '一个只需看着就能待很久的页面。先把地址留在这里。\nhttps://ciechanow.ski/moon/',
      topics: ['网页'],
      publishedAt: '2026-09-18T05:07:00.000Z',
    },
    {
      id: 'note-sample-august',
      body: '今天绕远路回家。多走了二十分钟，发现一家还开着的旧书店。',
      topics: ['日常'],
      publishedAt: '2026-08-30T11:30:00.000Z',
    },
  ].map((note) => ({
    ...base,
    ...note,
    kind: 'note' as const,
    title: '',
    summary: '',
    discussion: false,
  })),
]
